baseURL = "https://intelops.netlify.app"
languageCode = "en-us"
theme = "dtox-hugo"
title = "Intelops"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 6
[[menu.main]]
URL = "#pricing"
name = "Pricing"
weight = 4
[[menu.main]]
URL = "#team"
name = "Team"
weight = 3
[[menu.main]]
URL = "service"
name = "Service"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 5
[[menu.main]]
URL = "#feature"
name = "Feature"
weight = 1
[params]
author = "Vivek"
description = "Intelops Demo site"
googleAnalitycsID = "Your ID"
home = "Home"
logo = "images/logo.png"
[params.banner]
URL = "#"
bgImage = "images/hero-area/banner-bg.png"
btnText = "explore us"
content = "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum <br> dolore eu fugiat nulla pariatur."
image = "images/hero-area/banner-img.png"
title = "Take Control of your <br> Project and Team"
[params.banner.bgShape]
enable = false
[params.footer]
bgImage = "images/backgrounds/footer-bg.png"
[[params.footer.socialIcon]]
URL = "#"
color = "facebook"
icon = "ti-facebook"
[[params.footer.socialIcon]]
URL = "#"
color = "twitter"
icon = "ti-twitter-alt"
[[params.footer.socialIcon]]
URL = "#"
color = "linkedin"
icon = "ti-linkedin"
[[params.footer.socialIcon]]
URL = "#"
color = "black"
icon = "ti-github"
[params.navBtn]
URL = "#"
btnText = "Try Free"
enable = true
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/Venobox/venobox.css"
[[params.plugins.css]]
URL = "plugins/aos/aos.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/aos/aos.js"
[[params.plugins.js]]
URL = "plugins/Venobox/venobox.min.js"
[params.preloader]
enable = true
